### ISSUE TITLE
Alphabetical order

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#10]
Countries in "votes" https://staging.blockchainvsclimatechange.com/votes

 should be displayed in alphabetical order

**Comment by elf-pavlik** [comment]
now it orders itself by number of votes, most votes on top least on the bottom, do you prefer alphabetical? it may turn out that some countries starting with lower order letters will have very few votes and people will only see those 'above the fold'

**Comment by Tianguistengo** [comment]
that's a great point, let's leave it like it is
