### ISSUE TITLE
Stay in same place when click on country

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#11]
The way the staging version displays the names of the voters when clicked on country name should be the way it already does in gh-pages.

**Comment by elf-pavlik** [comment]
Will that work well for 100 and more votes per country?

**Comment by Tianguistengo** [comment]
we already put there a "load more" button that would display the total number of names 
but we need to href it so that it opens a new /path 
something like /Mexico /Suriname
and when the user wants to go back they can click "back" on their phone or "votes" on the bottom nav

**Comment by elf-pavlik** [comment]
Please check https://staging.blockchainvsclimatechange.com/

If you just have couple preview votes shown and link to 'show more' I don't think it makes sense to have additional step of showing and hiding those couple preview votes.

Please let me know if you really want this show & hide preview votes, I think having them shown right away makes more sense. You make the final call on how you want it.

BTW I set preview votes to 5 and 'load more' link only shows if country has more than 5 votes, to show it in action i added rest of the speedy gonzales crew to Mexico :wink:

**Comment by Tianguistengo** [comment]
That's a good suggestion pavlik, let's do it like that.

There is a little error. Instead of showing the names on a numbered list (showing the 5 most recent)
it's showing some weird symbol just before the name.

**Comment by elf-pavlik** [comment]
gh-pages doesn't have numbered list, just square bullet points: ■ . I played with custom character for those bullet points and now it has 'ballet box check mark' 🗹 as a test.

i think numbered (ordered) list wouldn't make sense but you can pick whatever UTF-8 character for bullet point style you like and change it here: https://github.com/elf-pavlik/blockchainvsclimatechange.com/blob/staging/style.css#L438

**Comment by Tianguistengo** [comment]
In this case we are gonna need the numbered list.
It is a fundamental part of the global strategy for each voter to know what number/place 
their individual vote was in the country and globe tally ( John Smith, example,  was  voter `#17` of albania, `#110` voter from the globe). This information has several advantages for voters and us in keeping count and registering votes correctly (marked in blockchain forever, more tamper-proof, less middle-man).

**Comment by elf-pavlik** [comment]
Do you plan just to rely on the order you put things in the spreadsheet? Also which number do you want to use in the preview and country full list of voters, the country or the globe?

**Comment by Tianguistengo** [comment]
only show country # in both preview and full list
the global # will be just mentioned when voted to the user and in the future we will have a global tally but there is not one now

I plan to backup that spreadsheet but if you have better recommendation to not lose that list ...is more than welcomed  :)

**Comment by elf-pavlik** [comment]
> only show country # in both preview and full list

done in 3b92089290ef64ac5473e8e68d5bc3ec6e96461f
