### ISSUE TITLE
support odd number of solutions

### ISSUE THREAD

**Issue by elf-pavlik** [elf-pavlik/blockchainvsclimatechange.com#13]
currently code to lay them into a zigzag assumes even number of solutions

**Comment by Tianguistengo** [comment]
we can just put an even # of solutions and solve this :)

**Comment by elf-pavlik** [comment]
yes, for now we need to keep even number but when i get a chance i'd still like to fix it so it doesn't break with odd number

**Comment by Tianguistengo** [comment]
it is highly unlikely that we will change the # of solutions but if you think its important it's ok :) thanks
