### ISSUE TITLE
bring to staging branch changes in gh-pages/info.html

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#16]
I had to make the changes gh-pages because they were not going live when I commited in staging branch

**Comment by elf-pavlik** [comment]
done, i also deleted `gh-pages` branch not to make any more changes over there

**Comment by Tianguistengo** [comment]
Thanks @elf-pavlik  the one you uploaded is not the same as I left it yesterday :(    should I re-do it?  It's just  words and styling missing

**Comment by elf-pavlik** [comment]
I still have `gh-pages` branch offline, I'll compare them again tomorrow
