### ISSUE TITLE
remove CSS for projects

### ISSUE THREAD

**Issue by elf-pavlik** [elf-pavlik/blockchainvsclimatechange.com#17]
HTML and ES already removed in https://github.com/elf-pavlik/blockchainvsclimatechange.com/commit/c9be6ef0869fa0cfd0084e22dea01a70f9975a80

**Comment by Tianguistengo** [comment]
based on the tag......can I help you?

**Comment by D-cypher** [comment]
Was the projects page completely removed? I can't navigate to it anymore

**Comment by Tianguistengo** [comment]
it's hidden because we won't use it in version 1.0 but we will in later versions

**Comment by elf-pavlik** [comment]
yes, i removed it but didn't remove the css part. we have no reason to keep it while we don't use it, later we can always find it in git history so we don't loose it completely

**Comment by Tianguistengo** [comment]
should we close this issue @elf-pavlik ?

**Comment by elf-pavlik** [comment]
let's leave it open with that *for later* label

**Comment by elf-pavlik** [comment]
done as part of recent cleanup
