### ISSUE TITLE
UI-Correct zig-zag order between boxes in /solutions

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#18]

**Comment by elf-pavlik** [comment]
Could you please explain it, i don't see anything obviously wrong there :eyeglasses:

**Comment by Tianguistengo** [comment]
sure,  the line that connects solution boxes goes from solution 2 to 4 , 
3 to 5 and so on and so forth

**Comment by elf-pavlik** [comment]
oh, so we don't need to fix the zig-zag just adjust order of solutions to match it?

**Comment by Tianguistengo** [comment]
that's one option but then it would look kinda non-intuitive :  
1-2
4-3
5-6

so maybe better if we leave the boxes the way they are now and maybe just make the line connectors go diagonal?

**Comment by elf-pavlik** [comment]
maybe you can try to work on that on a dedicated `zig-zag` branch?
https://code.visualstudio.com/Docs/editor/versioncontrol#_branches-and-tags

**Comment by Tianguistengo** [comment]
thanks for the link, I'll give it a go and ask diego to help with front-end if I get stuck :)
