### ISSUE TITLE
Is it possible to make repo owned by both you and me? want to access settings

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#22]

**Comment by elf-pavlik** [comment]
we can move it to an organization and than multiple members can have admin access

**Comment by Tianguistengo** [comment]
that'd be great

**Comment by elf-pavlik** [comment]
I moved it to @hackers4peace and gave you admin access, if you want you can keep it here or create new organization and move it there.

**Comment by Tianguistengo** [comment]
awesome, thanks, let's move this one too for the future :)  https://github.com/elf-pavlik/bvcc-banners
