### ISSUE TITLE
colour bottom sticky bar

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#25]
Dear Diego, this is probably the worst mockup I've done in my life but I just wanted to illustrate how the bottom sticky bar   1. Needs colours  (users are not even noticing them at the moment)
                                            2. Needs to highlight inside the circle so user know they are in that step (if she is in step 2 then step 1 and 2 need to be highlighted, if she is in step 3 then step 1. 2. and 3 should be highlighted)
                                            3. please change them all to blue, current colours  in my mockup 
are horrilbe
                                            4. as you can see the text  (solutions - vote-  info ) 
needs to be bigger than it was before

sorry for such bad mockup, and thanks for the help :)

**Comment by Tianguistengo** [comment]
![bottom stick bar with colours](https://user-images.githubusercontent.com/18708047/55531942-3c9d3000-5669-11e9-91a2-9b87604cb760.png)

**Comment by D-cypher** [comment]
Hey Sebastian,

I had already created a distinction in the steps to the last time I updated
to gh-pages. It seems those changes did not get carried over to the staging
branch. See image below:
- Grey (and filled) is previous step
- Green (and filled) is current step
- Outlined is a next step.

This design was more simple and not too obtrusive.

Also i can't get the staging branch to work locally. Do i need to install a
specific server?

[image: image.png]

*Kind Regards,*

*Diego Ameerali*
*Creative Explorer*

*2019 Local President*
*JCI Unify (Suriname)*

Call me +597 8812107
*Connect* with me on Instagram <https://www.instagram.com/diegoameerali/>,
Twitter <https://twitter.com/DiegoAmeerali> and Linkedin
<http://www.linkedin.com/in/diegoameerali/>
- - - - - - - - - - - - - - - - - - - - - - - - - - -
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by Tianguistengo** [comment]
yo yo @D-cypher  you are right, some changes in gh-pages didn't get carried into stating branch,
I'm working with pavlik on saturday and gonna ask him that.

Still, I've trialed the app with the sticky  nav and people fail to see it / click it 90% of the time.
Main problem is that it is white and does grab attention  ( I agree 3 colours it's too intrusive, maybe a variation of blue? I like this one https://research.google.com/seedbank) and bigger text-size but if you have a better suggestion it's very welcomed.

I'll let you know about the commits to staging (for now don't commit in github, you can see instructions on repo readme to use local host)
and please accept my invitation to the new github organization where I moved the repo :)
https://github.com/blockchain-vs-climate-change

have a good weekend :)

**Comment by Tianguistengo** [comment]
![progress bar with green](https://user-images.githubusercontent.com/18708047/55598374-8e989100-570f-11e9-977a-2cbdc558b62c.png)
