### ISSUE TITLE
Front-end for Form

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#26]
![image](https://user-images.githubusercontent.com/18708047/57198586-2c16f880-6f3a-11e9-8290-dd0aa9f6cc7e.png)

**Comment by Tianguistengo** [comment]
6 fields  in hierarchical order

1. Nationality
2. (Optional) Tell us in less than 100 words your opinion about how to solve climate change
3. (Optional) Five word description of yourself (organization/ company/ school/ profession)
4. First and Last Name
5. (tick box)over 18 years old
 (tick box) I accept the Privacy policy and terms of service
 -----------_needs to be linked here_
(tick box) Newsletter  (once or twice a month)
6. Google or Facebook Login

**Comment by D-cypher** [comment]
Just pushed the base of the form, still need to finish the styling. But the base can be implemented in the template with a trigger

**Comment by elf-pavlik** [comment]
I'll take a look at it today/tomorrow.

**Comment by D-cypher** [comment]
So steps 1-5 are done. Steps 6 just needs the social login buttons added.
