### ISSUE TITLE
When selecting a solution, checkbox shows text inline telling user "2 left", "1 left"

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#28]
When user selects a solution, checkbox should change to #1 when first one is selected, then 2 and 3 naturally............. then **Form** pops up

**Comment by elf-pavlik** [comment]
I think this may suggest that order people select it in matters, i think we can just have some sticky counter saying *please select 2 more to continue*.

**Comment by Tianguistengo** [comment]
that sounds better yeah,  and if we want to avoid a sticky counter we could also 
just display text inline saying _"select 2 more solutions to vote"_  and then 1

**Comment by elf-pavlik** [comment]
If you guys add it somewhere I can make number change as solutions get selected.

**Comment by D-cypher** [comment]
i added the a number between [ ] brackets after the select and a sticky counter on the bottom to indicate the amount of selections

**Comment by Tianguistengo** [comment]
awesome, I'll give it a go see how it works in different devices

**Comment by Tianguistengo** [comment]
I'm sorry to reopen this one guys, there might have been some confusion about the second sticky bar, we need to be consistent with UX across our platform and currently instructions in every page are on top of the page (we humans are used to reading top-bottom / left-right {not in every language but generally} )   so it doesn't seems coherent to put the instruction "select 3" on the bottom and to add another sticky bar (we already have one-) plus it might seem like it's a button and people might try to click it.

If you don't mind, let's just add the text ""_select 2 more solutions_" and "_select 1 more solution_"  just below the check box that the user clicks. I'll make sure to put in bold the text "select 3 solutions" at the top of the page as instructions.

Thank you very much and sorry for the confusion

**Comment by Tianguistengo** [comment]
we should just **hide** the second sticky nav bar just in case we notice that top instructions are not read/fail  and we might want to opt for adding the second sticky nav bar to try something different

**Comment by Tianguistengo** [comment]
not working in desktop

**Comment by Tianguistengo** [comment]
It's sort of confusing there are 2 instructions (at the top and in the new sticky bar) but let's see how it works

**Comment by elf-pavlik** [comment]
For me works in both firefox and chromium, maybe you could record screen to gif and post it here? For example using: https://github.com/phw/peek

**Comment by elf-pavlik** [comment]
I think those two instructions make sense, reading from the top one can firs see **SELECT 3** and will not see it any more once scrolling solutions, while selecting one will only see that sticky bar which shows how many still left.

**Comment by elf-pavlik** [comment]
![select-solutions](https://user-images.githubusercontent.com/876431/58893551-03f3f400-86b6-11e9-819f-5cbde6b6e580.gif)
