### ISSUE TITLE
reading more on Solutions-stay in tab

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#33]
when the user clicks on any solution, the drawdown link to that solution opens in a new tab and the user is taken to that new tab thus leaving our web app. Is there anyway for them to stay in our web app but notice that a new tab was opened alongside?

**Comment by elf-pavlik** [comment]
It looks that people tried to come up with various hacks to do that which don't work consistently across browsers. In general it looks like something that browsers intentionally don't support since it could allow to open tabs without person noticing it.
