### ISSUE TITLE
Expand element inline when user wants to read the full opinion on climate change from another user in the voters list

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#34]
in the voter's list, you can see the name of the voter plus her title/short description, 
I was thinking that  after the title we should also put the start of their answer to "how do you think climate change can be solved" (collected when they fill voting Form) because this information will be probably very appealing for other voters to read (and feel motivated to vote)

Inside of any country's voter list, I was thinking every voter should have 2 sentences designed for them (one on top of the other). First one is like its now: voter name + title. 
Second one is beginning of opinion and points like these ones {........} forgot their name

**Comment by elf-pavlik** [comment]
mostly done, one can click on visible paragraph to expand to the full text

**Comment by elf-pavlik** [comment]
@D-cypher I think I still left some styles for spans broken with my change in https://github.com/aliceingovernment/aliceingovernment.com/commit/33f4172aa2cb83e82745371e3e765dffcc92f0bc
Please take a look at it when you work on improving styles to close this issue.

**Comment by Tianguistengo** [comment]
This is looking great, one change please:

Every voter should have max 3 text lines devoted to them (otherwise there is too much info on a small space)
**line 1:**  voter name + title 
**line 2:** beginning of opinion and points like these ones {........} to expand rest of opinion inline

It is common for the name+title to take 2 lines rather than 1, if this happens the Opinion should start and finish in line 3, if it doesn't it should start and finish in line 2

**Comment by elf-pavlik** [comment]
Opinion needs to start on its own line, so we should count 2-3 lines for name + description and after that opinion. Currently I have it set to show first 3 lines, I don't think we should show less than 2 since it will not even fit a full short sentence.

**Comment by Tianguistengo** [comment]
that sounds good
2 lines max for name + description
2 lines max for opinion and then points (....)

**Comment by elf-pavlik** [comment]
ok, staging leaves only two lines now

**Comment by Tianguistengo** [comment]
awesome!
