### ISSUE TITLE
Hard limit on # of words

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#35]
hard limit of 100 words for opinion and 5 for title (both while filling the voting Form)

so that the user is unable to write beyond that number

**Comment by elf-pavlik** [comment]
Usually text area would show characters count, should we go with 40 for title and 500 for opinion?

**Comment by elf-pavlik** [comment]
I will just use [`maxlength`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#Min_and_max_length) for now and later we'll add some nice counter so that people see how many characters they still have left.

**Comment by Tianguistengo** [comment]
yeah `maxlength` is perfect for now. The text instruction already says "in less than a 100 words tell us ...." so that should be enough.

I've thought about increasing # of words for both title and opinion but came to the realization that it's best to leave it short for the beginning of the experiment. We should evaluate it again later because I'm sure some users will want more word space to express their opinions. One great advantage of just having 100 words is that you have to get to the point straight away (which is something that we humans rarely do, we love stories)
