### ISSUE TITLE
Automatic email  user receives when she votes

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#38]
- Email says

 _Congratulations on being part of this citizen vote on Climate Change_

_If you wish to read more about Alice in Government and how to get involved please visit ---link here to /info {on FAQs section if possible}_

Twitter and Medium icon links
Estonian Address  _Kiriku 6, Tallinn, 10130, Estonia_

**Comment by elf-pavlik** [comment]
I think I will start with plain text email and later once you design HTML email we can change it.

**Comment by Tianguistengo** [comment]
sounds good, does our MailChimp account is useful here or will you do it externally?
User Roboto Mono if possible https://fonts.google.com/specimen/Roboto+Mono

**Comment by elf-pavlik** [comment]
I did the plain text mail version and will deploy it tomorrow. When you have HTML email designed you can create new issue about adding it.

**Comment by Tianguistengo** [comment]
add new **twitter link** from bvcc to alice in gov (Medium one requires us to contact them to change them, I've submitted a ticket)
https://twitter.com/aliceingov

**Add label to sender** "Alice in Government" no-reply@aliceingovernment.com

**Subject/title of email** "Your vote was registered successfully"

**Content of email:**

Congratulations on being part of this citizen vote on Climate Change.

If you wish to read more about Alice in Government and how to get involved please visit ---_link here to /info {on FAQs section if possible}_

_Twitter and Medium icon links_
Estonian Address Kiriku 6, Tallinn, 10130, Estonia
