### ISSUE TITLE
voting Form stays on top of pages when navigating away

### ISSUE THREAD

**Issue by D-cypher** [elf-pavlik/blockchainvsclimatechange.com#39]
@elf-pavlik can you check the form, it's stays above the other pages when people don't completely finish it and navigate away.

**Comment by elf-pavlik** [comment]
Actually when i wrote code to manage selecting solutions, after selecting 3 it was hiding all the rest as well as navigation footer. This way person would normally would focus on completing the vote and not navigate to other page. Of course we need to support case where someone would click back button.

I think we may also need to add some kind of 'abort' option if someone changes one's mind and doesn't want to complete the vote.

**Comment by Tianguistengo** [comment]
I love the idea of removing all elements (solutions, nav bar, etc.) when completing the form so users can focus.

Maybe a simple X for closing should be enough to abort. It should take you to /solutions but without your solutions selected

**Comment by elf-pavlik** [comment]
I think we have enough space on the screen to keep showing on top which solutions someone selected, maybe just make them little more compacted. I'll look into that...
