### ISSUE TITLE
If user doesn't tick mandatory check boxes display text saying...

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#42]
if user doesn't tick mandatory check boxes we should display some text saying _Please fill this to continue_

Regarding which are the mandatory steps, from the 6 steps explained in issue #43 only step 2 and 3 are optional (100 word opinion and 5 word description), the rest of them need the _Please fill this to continue_  notice if not filled

**Comment by elf-pavlik** [comment]
For now it invalid field shows pink and person can't go forward until fixing it. I think we may need more than one validation texts for each 3 of the required form steps.

**Comment by Tianguistengo** [comment]
I really think a simple text saying _Please fill this to continue_  would do wonders for now (in all 4 steps that are mandatory: name, nationality, checkboxes, Google/FB login

Later we can get creative with personalized texts for each step not filled
