### ISSUE TITLE
Changes to landing site 

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#44]
Let's make our landing site non-scrollable (all content fits on first view and there is nothing below so no possibility to scroll)

The idea is for the user to enter our site, see a compelling message, 
and then start on step 1 (list of voters).

For this we need to put logo, compelling text, and then line with pointer to step one on bottom nav bar.

**Comment by elf-pavlik** [comment]
Please remember that one can't really make to many assumptions about screen sizes. Keeping things short can make it that in most cases everything will fit on single screen but for some people it may still end up scroll able.

> For this we need to put logo, compelling text, and then line with pointer to step one on bottom nav bar.

I don't understand what do you mean by that

**Comment by Tianguistengo** [comment]
That's good info elf,  I didn't know that. Is there any smart solution like `fit content to screen size`  or some clever fix like that?

Here is an ugly draft of how I imagine the landing site, sorry for my bad Paint skills

![landing paint](https://user-images.githubusercontent.com/18708047/58599194-cf5ee300-8244-11e9-81f4-805fb989023d.png)

**Comment by Tianguistengo** [comment]
blue-purple is  # 4366AE

**Comment by elf-pavlik** [comment]
If you keep it that short it will simply fit on most of the screens

**Comment by Tianguistengo** [comment]
but will it not look tiny if you open it in a massive screen?

**Comment by Tianguistengo** [comment]
I opened it on a friend's iphone and the arrow pointing to step 1 was a weird pointer icon, is this normal?

**Comment by elf-pavlik** [comment]
It seems to use simple unicode symbol ↙ you could take screenshot and share it here

https://github.com/blockchain-vs-climate-change/blockchainvsclimatechange.com/blob/8ce8963acdd2aac23edf84b77caa1cd9fe621ff9/index.html#L42

**Comment by D-cypher** [comment]
Changed it to fully CSS
