### ISSUE TITLE
3 overflows

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#45]
-voter counter for votes received by countries in /voters          _desktop and mobile_

-long country names in /voters      _desktop and mobile_ 

-long solution names in /solutions     _on mobile_

**Comment by Tianguistengo** [comment]
![image](https://user-images.githubusercontent.com/18708047/58916477-687c7680-86e9-11e9-8c21-6c3344669825.png)

**Comment by elf-pavlik** [comment]
I suggest you just use flexbox instead of relative positioning, you can have counter side fixed width and the side with country name flex

**Comment by Tianguistengo** [comment]
@elf-pavlik  center voter counter pls :)

**Comment by Tianguistengo** [comment]
![image](https://user-images.githubusercontent.com/18708047/59647226-03d90700-9140-11e9-9c7f-60540ddd508a.png)

**Comment by Tianguistengo** [comment]
![image](https://user-images.githubusercontent.com/18708047/59647319-55819180-9140-11e9-8219-954b2045dd98.png)

**Comment by Tianguistengo** [comment]
the only task remaining to close this issue is to center the white box with # of voters because it currently appears way too high on the black bar, you can see it in the last picture I posted here with the Poland example
