### ISSUE TITLE
looking for a yes or no answer on what does a user sees once she comes back to site after voting 

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#48]
Bonus question. If I already voted, went for a run, come back to my laptop and go to our website, I will land in /info  where I currently see my name in my country's list but if 10 days go by perhaps 5 more people from my country have voted so I will see the last 5 (which will not include me) right? this would be ok, I just want to figure out if that's the case

**Comment by elf-pavlik** [comment]
I have just changed it that it always shows your vote (and only your vote) on info page in country box of your nationality. If you want different behavior let's create new issue and describe how exactly it should behave.
