### ISSUE TITLE
Reset scroll position

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#5]
when I click on some solutions they appear on the top but others on the bottom :(

**Comment by elf-pavlik** [comment]
I should take inspiration from:
* https://router.vuejs.org/guide/advanced/scroll-behavior.html
* https://medium.com/lacolaco-blog/introduce-router-scroller-in-angular-v6-1-ef34278461e9

**Comment by elf-pavlik** [comment]
used snippet from: https://github.com/Polymer/pwa-helpers/pull/14
