### ISSUE TITLE
add Privacy Policy and Terms of Service

### ISSUE THREAD

**Issue by elf-pavlik** [elf-pavlik/blockchainvsclimatechange.com#51]
Now index.html have placeholders `id="privacy-policy"` and `id="terms-of-service"` where the content should go.

ping @Tianguistengo

**Comment by elf-pavlik** [comment]
You can see initial content on
* https://staging.aliceingovernment.com/terms-of-service
* https://staging.aliceingovernment.com/privacy-policy

Links in the form work already, someone still needs to
* add links to the footer
* style both pages

**Comment by Tianguistengo** [comment]
thanks :)

**Comment by Tianguistengo** [comment]
when copying from drive to code is there any way to keep some of the drive styling? like bold or underlying?

**Comment by elf-pavlik** [comment]
you can use html and css to reproduce it

**Comment by Tianguistengo** [comment]
ok so from what I understand there is no way to import it, just do it again  word by word with html and css, I'll get into that
