### ISSUE TITLE
countries voter counter is empty now

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#52]
![image](https://user-images.githubusercontent.com/18708047/58849809-8ac2b580-8651-11e9-9f33-270787e72568.png)

**Comment by elf-pavlik** [comment]
It has white text on white background @D-cypher it ended up like that after i made selectors more specific with classes. I'll leave it to you since I don't recall which styles supposed to apply to which elements.
