### ISSUE TITLE
in /info we are missing text above new voter 

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#57]
After the user fills the voting form, she lands in /info and we already show the new voter's name in her country list but we are missing the text before it saying "**Congratulations on being part <br> of this citizen vote on climate change**"

![image](https://user-images.githubusercontent.com/18708047/59007599-bc23b880-87ec-11e9-8377-027a7cec10c7.png)

**Comment by D-cypher** [comment]
Added this in the static view. Still needs to be added in template to only appear after vote @elf-pavlik

**Comment by Tianguistengo** [comment]
it seems to me like this is done, anybody can confirm?
