### ISSUE TITLE
homepage not responsive on big screens

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#63]
![not responsive](https://user-images.githubusercontent.com/18708047/59546521-5920d880-8ef4-11e9-80e2-72bb986a3001.png)

**Comment by elf-pavlik** [comment]
I don't think it ever was designed as responsive? What would you expect to change on a big screen?

**Comment by D-cypher** [comment]
What elf says is correct, it never was designed as responsive. We decided at the start to give it a fixed width (in this case 480px). The height is determined by the browser size

**Comment by Tianguistengo** [comment]
all the other pages in our web app respond well to different screens,
could we just make the homepage responsive or would that be too much chaos to other pages?

**Comment by Tianguistengo** [comment]
the problem with the homepage not being responsive is that if someone opens it in a big screen the first impression would be "this whole web app is not serious" just because of this small thing we didn't cater to

**Comment by elf-pavlik** [comment]
We made the text vertically centered in one of the recent commits. I'll close this issue and we can always open one, preferably with concrete proposal on how we need to change something.
