### ISSUE TITLE
if you have been in /info before voting.........

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#66]
if you have been in /info before voting and after that you vote, when you register your vote you will land in /info like intended but not at the top of the page where you can see the "congrats for voting, you are #45 voter from Scotland" but you will land at the scroll place where you left /info last time thereby not seeing that your vote was registered successfully.

**Comment by elf-pavlik** [comment]
I can't reproduce it, if you can please record it as gif with https://github.com/phw/peek

**Comment by Tianguistengo** [comment]
I'm gonna check if it still happens once we migrate the "congratulations" and country box with new voter to /voters

will make a note to remember
