### ISSUE TITLE
Change country list so that it appears per country name alphabetically and not per 2 letters country code (DE,CH,MX)

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#67]

**Comment by Tianguistengo** [comment]
This is still happening in all user tests

**Comment by elf-pavlik** [comment]
I've fixed it 2 days ago, can you please check it making sure you hard reload your browser first?

**Comment by Tianguistengo** [comment]
ah ok, I didn't realize you changed this 2 days ago, I just checked it in 3 different browsers and it seems to work good, thanks!
