### ISSUE TITLE
Flags appear as 2 letter code (MX) rather than flag image

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#76]

**Comment by Tianguistengo** [comment]
I've seen that happening in at least 5 user tests, it's weird how it happens in some but not others

**Comment by elf-pavlik** [comment]
We use emojis for flags, have you noted device model, operating system version and browser?

**Comment by Tianguistengo** [comment]
I did but it happened in 5-6 different devices, operating systems, most of them desktop/microsoft/chrome

**Comment by elf-pavlik** [comment]
Some pointers: https://twitter.com/maximeeuziere/status/1030165022809448448

**Comment by elf-pavlik** [comment]
I'll try detecting OS https://gist.github.com/hkulekci/3433850
And if Windows using svg flags instead of emoji flags: http://flag-icon-css.lip.is/

**Comment by Tianguistengo** [comment]
diego also confirms that is chrome where he cannot sees the flags, in firefox its ok
