### ISSUE TITLE
Dancing dudes disappear for laptops

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#78]
I have been trying in different computer screens and it seems that the dancing dudes disappear in most laptops :( 

I think we need to make sure that they don't disappear on tablets and laptops, otherwise the space is too big 

![image](https://user-images.githubusercontent.com/18708047/62816264-e1cd8680-bae9-11e9-8366-ff2ea7e4c8bb.png)

**Comment by elf-pavlik** [comment]
I'll take a look at it, i've set it to don't show if page has less than 650px height, maybe it needs little less, will look for smaller value!

**Comment by Tianguistengo** [comment]
yeah I think that would work, thanks!

**Comment by Tianguistengo** [comment]
Is there any way to make a  homepage into the same ui across all screen sizes? so that regardless of the screen size it will look exactly like the image below. I tried searching it but couldnt find much 

Like a poster in a wall

![image](https://user-images.githubusercontent.com/18708047/62827757-c6bb4f00-bb9b-11e9-9825-45aee76c6c12.png)

**Comment by Tianguistengo** [comment]
did you adjust this already elf? I ask because I can see the dancing dudes in my laptop again

**Comment by Tianguistengo** [comment]
if the feet are cut is ok........... it's better if image appear in more screen sizes

**Comment by Tianguistengo** [comment]
looks done in staging
