### ISSUE TITLE
odd voter 

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#79]
There's a voter recoreded in our database but the only record is the user's email. No country, solutions, accepted terms, etc..... and user doesn't appear in /voters....... what could this mean?

**Comment by Tianguistengo** [comment]
user put a hotmail account somehow

**Comment by elf-pavlik** [comment]
It looks like someone logged in but then vote wasn't successfully sent. You could email the person asking to try again.

**Comment by Tianguistengo** [comment]
but how could they login with a hotmail account? and how could they login without choosing any solutions or accepting terms?

**Comment by elf-pavlik** [comment]
They used google or facebook login, and they have google or facebook account registered for their hotmail email address.

They way it works
1. Person fills up the form and clicks login with ...
2. Information gets saved in browser and they get redirected to google or facebook (via our backend)
3. They approve logging in on google or facebook and get redirected back to our backend
4. our backend redirects back to the page and then it sends the data saved in to browser

it looks like the last part of step 4 somehow failed, it could happen if person closes the tab right after getting redirected back, page needs to load first before it will send data to the backend.

**Comment by Tianguistengo** [comment]
Thanks for explaining it, this clarifies it very well
