### ISSUE TITLE
Automatically add flag when country name entered

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#8]
In the voter spreadsheet we'll have the name of the country of the voter, how do we make sure that we don't have to add the flag for each voter and rather the flag shows for every country entered automatically?

**Comment by D-cypher** [comment]
This is some scripting that is beyond my current capabilities. Maybe we can use the country code to pull up the flags. Currently the flags can be pulled from a library where as only the country code is variable.

**Comment by Tianguistengo** [comment]
yeah no worries mate, hopefully elf pavlik knows

**Comment by elf-pavlik** [comment]
https://staging.blockchainvsclimatechange.com/votes already does it using emoji flags via this package https://www.npmjs.com/package/country-emoji

**Comment by elf-pavlik** [comment]
You just need to make sure to use English spelling of the country name in the spreadsheet
