### ISSUE TITLE
First voter's opinion doesn't appear if you enter country

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#82]
If a country has more than 4-5 voters you can click the "load more" to enter to the country page and see all voters. Everything is fine except the opinion of first voter cannot be seen, Image here 
°
°

![image](https://user-images.githubusercontent.com/18708047/63204268-86584700-c05b-11e9-8797-5af23acd5061.png)

**Comment by elf-pavlik** [comment]
I see, that view misses padding on the bottom to avoid sticky nav ending up over the text.
