### ISSUE TITLE
user full url of sulution instead of just rank index

### ISSUE THREAD

**Issue by elf-pavlik** [elf-pavlik/blockchainvsclimatechange.com#84]
this will make votes self containing and immune to rank indexes ever changing

**Comment by Tianguistengo** [comment]
Can we put them alphabetically by last name?

**Comment by elf-pavlik** [comment]
Now vote stores full URL (on drawdown.org) for each selected solution, this way if solution rank ever changes it will not affect interpretation of votes.

> Can we put them alphabetically by last name?

Not sure what you mean by that, maybe didn't describe this issue here clearly enough.

**Comment by Tianguistengo** [comment]
sorry for the confusion, I thought this issue was about voters index shown in /voters 

Since voter's rank has been removed I thought it'd be a good idea to arrange them by last name

**Comment by elf-pavlik** [comment]
currently voters get listed in reversed chronological order - most recent voters on top
