### ISSUE TITLE
seems like votes also show their voting date on the UI in /voters, not sure if the change its intentional or not

### ISSUE THREAD

**Issue by Tianguistengo** [elf-pavlik/blockchainvsclimatechange.com#85]

**Comment by Tianguistengo** [comment]
![image](https://user-images.githubusercontent.com/18708047/66606052-e1e41400-eb76-11e9-906b-73f41e85d9e5.png)

**Comment by Tianguistengo** [comment]
photo taken from staging site

**Comment by elf-pavlik** [comment]
When I removed that per country vote index I added instead date when the vote was placed. Also as I mentioned in another issue, votes stay ordered in reverse chronological order.

I can easily remove that vote date if you like.

**Comment by Tianguistengo** [comment]
for now is good, just wasn't sure if it was intended or not, seems a bit like not the most needed info to see as a user,
maybe to index voters by last name would be good now
